### ISSUE TITLE
Flatpak needs the `dri` permission to launch

### ISSUE THREAD

**Issue by aunetx** [RogerCrocker/BadaBib#4]
When trying to launch after installing from flatpak, the app crash with the following error:

```
libEGL warning: MESA-LOADER: failed to retrieve device information

libEGL warning: DRI2: could not open /dev/dri/card0 (Aucun fichier ou dossier de ce type)
libGL error: MESA-LOADER: failed to retrieve device information
No provider of glGetShaderiv found.  Requires one of:
    Desktop OpenGL 2.0
    OpenGL ES 2.0
```

Adding the `dri` permission in flatseal makes the app work, so maybe adding it as a default would be better!

However, I don't really know why it would use the gpu, as this permission is normally not needed for graphical apps that do have a direct access to the gpu...

**Comment by RogerCrocker** [comment]
Thanks for the bug report and the patch! I'm sorry, I have no idea what might cause this bug. There is [this issue](https://github.com/flathub/org.gnome.meld/issues/10), which seems to be the same problem, but doesn't provide much insight  either. Anyhow, for now I don't see a problem with adding the dri permission to the flatpak.
