### ISSUE TITLE
Abstract is unreadable in dark mode adwaita. 

### ISSUE THREAD

**Issue by vasholotl** [RogerCrocker/BadaBib#7]
**Here's what it looks like in light mode of a sample article**
![image](https://user-images.githubusercontent.com/48813136/169211294-d0d5bbfc-f70b-4af0-97be-daf369106bda.png)

**Here's what it looks like in dark mode**
![image](https://user-images.githubusercontent.com/48813136/169211367-c574f551-68de-435b-b794-092ad474cc1b.png)

The text box should either keep the dark text or switch the background color of the abstract text box to a darker color for better contrast. I think the second solution would be better suited for dark mode.

**Comment by RogerCrocker** [comment]
Hi! This is strange. Is this the Flatpak version? And are you using a custom GTK theme? 

This is what the abstract looks like for me:

![Screenshot_Abstract](https://user-images.githubusercontent.com/88910328/169419260-feccf671-b76e-495b-b2c2-19839d8d454e.png)

**Comment by vasholotl** [comment]
Hello! I am using the flatpak version on Fedora 36 but no custom GTK theme, just default adwaita dark theme. I found something interesting about the bug. If dark mode is turned on in the Baba Bib! preferences it renders the text box color correctly but if it's done by the built-in Gnome settings method the bug occurs. You can leave dark mode permanently on of course but it wouldn't respect the Gnome light/dark mode and it doesn't work well with extensions that changes the mode automatically depending on the time.

**Comment by RogerCrocker** [comment]
Right, that makes sense. Bada Bib! applies some style changes on top of the ones triggered by the system. This is to work around a [missing style class](https://gitlab.gnome.org/GNOME/libadwaita/-/issues/353) in libadwaita. I think there is a way to make sure that these changes are also applied when the system wide theme changes, but I need to look into that...

**Comment by RogerCrocker** [comment]
The latest commits should have fixed this issue. I'll try to make a bug fix release within the next couple of days.
